import type { Metadata } from 'next'
import Navbar from './components/Navbar'
import './globals.css'


export const metadata: Metadata = {
  title: 'Ebenezers Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="mytheme">
      <body>
        <Navbar></Navbar>
        <main className='w-11/12 mx-auto'>
          {children}
        </main>
      </body>
    </html>
  )
}
