import type { Metadata } from "next";
import ThemeProvider from "@/components/theme/theme-provider";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { BackgroundBeams } from "@/components/ui/background-beams";

export const metadata: Metadata = {
  title: "Ebenezer Zergabachew",
  description: "Generated by Ebenezer Zergabachew",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={`wrapper`}>
      <body className="pb-20 lg:mt-0">
        <div className="lg:w-full max-w-screen-lg mx-auto rounded-md relative lg:flex flex-col antialiased px-5">
          <ThemeProvider>
            <Navbar />
            <div className="mt-12">{children}</div>
          </ThemeProvider>{" "}
        </div>
        <BackgroundBeams className="z-[-10]"></BackgroundBeams>
      </body>
    </html>
  );
}
